Mirror kwargs in pandas for holiday
I am having trouble using `cudf` with `exchange_calendars` due to `cudf` overriding the pandas holiday and passing through kwargs and args incorrectly:

```
│ /home/xxx/dev/xxx/venv/lib/python3.10/site-packages/exchange_calendars/exchange_calendar │                                                                                                             
│ _xkrx.py:27 in <module>                                                                          │                                                                                                             
│                                                                                                  │                                                                                                             
│    26 from .precomputed_exchange_calendar import PrecomputedExchangeCalendar                     │                                                                                                             
│ ❱  27 from .xkrx_holidays import (                                                               │                                                                                                             
│    28 │   krx_regular_holiday_rules,                                                             │                                                                                                             
│                                                                                                  │                                                                                                             
│ /home/xxx/dev/xxx/venv/lib/python3.10/site-packages/exchange_calendars/xkrx_holidays.py: │                                                                                                             
│ 1125 in <module>                                                                                 │                                                                                                             
│                                                                                                  │                                                                                                             
│   1124 # Korean regular holidays                                                                 │                                                                                                             
│ ❱ 1125 NewYearsDay = KoreanSolarHoliday(                                                         │                                                                                                             
│   1126 │   "New Years Day", month=1, day=1                                                       │                                                                                                             
│                                                                                                  │                                                                                                             
│ /home/xxx/dev/xxx/venv/lib/python3.10/site-packages/exchange_calendars/pandas_extensions │                                                                                                             
│ /holiday.py:53 in __init__                                                                       │                                                                                                             
│                                                                                                  │                                                                                                             
│    52 │   │   self.tz = tz                                                                       │                                                                                                             
│ ❱  53 │   │   if self.start_date is not None:                                                    │                                                                                                             
│    54 │   │   │   if self.tz is None and self.start_date.tz is not None:                         │                                                                                                             
╰──────────────────────────────────────────────────────────────────────────────────────────────────╯                                                                                                             
AttributeError: 'KoreanSolarHoliday' object has no attribute 'start_date'
```

This makes sure that all the args and kwargs are mirrored correctly.